### ISSUE TITLE
New way to capture screenshot

### ISSUE THREAD

**Issue by wooly905** [wooly905/Project2020#11]
Currently, capturing screenshot is leveraged by using System.Windows.Form in Windows OS class. This won't work in a scenario of Remote Desktop session is closed. 
Need to find a new alternative to capture screen in Windows OS class.

**Comment by yihcheng** [comment]
Tried GDI+ and the result is the same like what we had by using System.Windows.Forms
Screen capturing will fail when remote desktop window is minimized or closed.
Make it open issue. No ETA.
